version: '3'
services:
  dotnet-builder:
    image: microsoft/dotnet:latest  # Use the .NET image as the base
    container_name: dotnet-builder
    volumes:
      - ./your-dotnet-app:/app   # Mount your .NET app directory to /app in the container
    working_dir: /app             # Set the working directory to /app in the container
    command: dotnet publish -c Release -o /publish-output  # Build the .NET app and publish the result
    networks:
      - app-net

networks:
  app-net:
